[project]
name = "lang-graph-project"
version = "0.1.0"
description = "LangGraph project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-groq>=1.1.3",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "langsmith>=0.13.0",
    "pygraphviz>=2.0.2",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
